# Generated by Django 5.2 on 2025-05-02 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Введите наименование категории товаров",
                        max_length=150,
                        verbose_name="Наименование категории товаров",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Введите категории товаров",
                        null=True,
                        verbose_name="Описание категории товаров",
                    ),
                ),
            ],
            options={
                "verbose_name": "категория товаров",
                "verbose_name_plural": "категории товаров",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Введите наименование продукта",
                        max_length=150,
                        verbose_name="Наименование продукта",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Введите описание продукта",
                        null=True,
                        verbose_name="Описание продукта",
                    ),
                ),
                (
                    "product_image",
                    models.ImageField(
                        blank=True,
                        help_text="Загрузите изображение продукта",
                        null=True,
                        upload_to="product/images",
                        verbose_name="Изображение продукта",
                    ),
                ),
                (
                    "purchase_price",
                    models.FloatField(
                        help_text="Введите стоимость продукта",
                        verbose_name="Стоимость продукта",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(verbose_name="Дата регистрации продукта"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        verbose_name="Дата последнего изменения информации о продукте"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        help_text="Введите категорию продукта",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products",
                        to="catalog.category",
                        verbose_name="Категория продукта",
                    ),
                ),
            ],
            options={
                "verbose_name": "продукт",
                "verbose_name_plural": "продукты",
                "ordering": ["name", "category", "created_at", "updated_at"],
            },
        ),
    ]
