# Generated by Django 5.2 on 2025-05-02 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["name", "category", "price", "created_at", "updated_at"],
                "verbose_name": "продукт",
                "verbose_name_plural": "продукты",
            },
        ),
        migrations.RenameField(
            model_name="product",
            old_name="purchase_price",
            new_name="price",
        ),
        migrations.AlterField(
            model_name="product",
            name="created_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата регистрации продукта"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="updated_at",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="Дата последнего изменения информации о продукте",
            ),
        ),
    ]
