# Generated by Django 5.2 on 2025-05-24 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_alter_product_category_alter_product_created_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": [
                    "name",
                    "category",
                    "price",
                    "created_at",
                    "updated_at",
                    "views_counter",
                ],
                "verbose_name": "продукт",
                "verbose_name_plural": "продукты",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="views_counter",
            field=models.PositiveIntegerField(
                blank=True, default=0, verbose_name="Счётчик просмотров"
            ),
        ),
    ]
