# Generated by Django 4.2.2 on 2025-06-01 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_alter_product_options_product_views_counter"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": [
                    "name",
                    "category",
                    "price",
                    "created_at",
                    "updated_at",
                    "views_counter",
                ],
                "permissions": [
                    ("can_unpublish_product", "Can unpublish product"),
                    ("can_delete_any_product", "Can delete any product"),
                ],
                "verbose_name": "продукт",
                "verbose_name_plural": "продукты",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="can_unpublish_product",
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
