# Generated by Django 4.2.2 on 2025-06-01 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_product_owner"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="can_unpublish_product",
        ),
        migrations.AddField(
            model_name="product",
            name="publish_product",
            field=models.BooleanField(
                blank=True, default=False, verbose_name="Публикация на сайте"
            ),
        ),
    ]
