# Generated by Django 5.2 on 2025-05-16 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Введите название блога",
                        max_length=150,
                        verbose_name="Название блога",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True,
                        help_text="Введите содержание блога",
                        null=True,
                        verbose_name="Содержание блога",
                    ),
                ),
                (
                    "preview",
                    models.ImageField(
                        blank=True,
                        help_text="Загрузите изображение для блога",
                        null=True,
                        upload_to="blog_app/images",
                        verbose_name="Изображение для блога",
                    ),
                ),
                ("publication_sign", models.BooleanField(blank=True, default=False)),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания блога"
                    ),
                ),
                (
                    "views_number",
                    models.IntegerField(
                        blank=True, default=0, verbose_name="Количество просмотров"
                    ),
                ),
            ],
            options={
                "verbose_name": "продукт",
                "verbose_name_plural": "продукты",
                "ordering": ["title", "publication_sign", "created_at", "views_number"],
            },
        ),
    ]
