# Generated by Django 5.2 on 2025-05-18 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blog",
            options={
                "ordering": [
                    "title",
                    "publication_sign",
                    "created_at",
                    "views_counter",
                ],
                "verbose_name": "продукт",
                "verbose_name_plural": "продукты",
            },
        ),
        migrations.RemoveField(
            model_name="blog",
            name="views_number",
        ),
        migrations.AddField(
            model_name="blog",
            name="views_counter",
            field=models.PositiveIntegerField(
                blank=True, default=0, verbose_name="Счётчик просмотров"
            ),
        ),
        migrations.AlterField(
            model_name="blog",
            name="content",
            field=models.TextField(
                blank=True, null=True, verbose_name="Содержание блога"
            ),
        ),
        migrations.AlterField(
            model_name="blog",
            name="preview",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="blog_app/images",
                verbose_name="Изображение для блога",
            ),
        ),
        migrations.AlterField(
            model_name="blog",
            name="title",
            field=models.CharField(max_length=150, verbose_name="Название блога"),
        ),
    ]
