# Generated by Django 5.2 on 2025-05-18 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog_app", "0002_alter_blog_options_remove_blog_views_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="title",
            field=models.CharField(max_length=250, verbose_name="Название блога"),
        ),
    ]
