# Generated by Django 5.2 on 2025-05-18 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog_app", "0003_alter_blog_title"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blog",
            options={
                "ordering": [
                    "title",
                    "publication_sign",
                    "created_at",
                    "views_counter",
                ],
                "verbose_name": "статья",
                "verbose_name_plural": "статьи",
            },
        ),
    ]
